title: |
  Banana For Scale
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.1698473
  brandStrength: 0.01895542582497001
  lightness: 0.3763441
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  rhythmicContrast: 0.1756272
typography_spectrum: 0.3691756
description: Providing Context and Excitement
layout_spectrum: 0.546595
name: Banana for Scale
